type Book @table {
  id: UUID! @default(expr: "uuidV4()")
  title: String!
  author: String!
  isbn: String @unique
  genre: [String!]!
  synopsis: String
  publicationYear: Int
  pages: Int
  rating: Float @default(value: 0.0)
  coverUrl: String
  createdAt: Timestamp! @default(expr: "request.time")
  updatedAt: Timestamp! @default(expr: "request.time")
}

type User @table {
  id: UUID! @default(expr: "uuidV4()")
  name: String!
  email: String! @unique
  createdAt: Timestamp! @default(expr: "request.time")
}

type ReadingList @table {
  id: UUID! @default(expr: "uuidV4()")
  userId: UUID!
  bookId: UUID!
  status: String! # "want_to_read", "reading", "completed"
  dateAdded: Timestamp! @default(expr: "request.time")

  user: User! @ref(fields: "userId", references: "id")
  book: Book! @ref(fields: "bookId", references: "id")
}